version: '3.4'

x-common-variables: &common-variables
 CELERY_BROKER_URL: redis://redis:6379
 CELERY_RESULT_BACKEND: redis://redis:6379
 MYSQL_HOST: mysql
 MYSQL_ROOT_PASSWORD: mysql123
 MYSQL_USER: mysql
 MYSQL_PASSWORD: mysql123
 MYSQL_DATABASE: hse-api-database
 RESTRICTED_MODE: 0

services:
 hse-api-web:
  build: .
  ports:
    - "80:80"
  depends_on:
    - redis
    - mysql
    - hse-api-celery
  environment: *common-variables
  volumes:
    - type: bind
      source: ./data
      target: /data

 hse-api-celery:
  build: .
  command: celery -A main.celery worker
  depends_on:
    - redis
    - mysql
  environment: *common-variables
  volumes:
    - type: bind
      source: ./data
      target: /data

 mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment: *common-variables

 redis:
  image: redis:latest
